gestion_empleados/views.py
from flask import (
    Flask,
    abort,
    render_template,
    blueprints,
    request,
    redirect,
    url_for,
    session,
    flash,
    send_file,
)
from werkzeug.security import check_password_hash, generate_password_hash
from forms import FormEmpleado, LoginEmpleado, DesempenioEmpleado, CambiarPassEmpleado
from markupsafe import escape
from db import get_db
import functools
import sqlite3

SALT = "Mt1c2022%$Gp443qu1p09"
main = blueprints.Blueprint("main", __name__)
main.register_error_handler(404, "perfil.html")


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        # puedes hacer otro tipo de validación
        if "id_empleado" not in session:
            return redirect(url_for("main.login"))
        return view(**kwargs)

    return wrapped_view


@main.route("/", methods=["GET", "POST"])
def login():
    form_login = LoginEmpleado()
    if request.method == "GET":
        return render_template("login.html", form=form_login)
    if request.method == "POST":
        usuario = escape(request.form["user"])
        clave = escape(request.form["password"])

        db = get_db()
        # sql = "select * from usuario where usuario = '{0}' and clave= '{1}'".format(usuario, clave)
        user = db.execute(
            "SELECT * FROM tbl_empleados WHERE identificacion = ? ", (usuario,)
        ).fetchone()
        db.commit()
        db.close()

        if user is not None:

            print(user[15])
            clave = SALT + clave + usuario

            sw = check_password_hash(user[15], clave)

            if sw:
                session["id_empleado"] = user[0]
                session["nombres"] = user[1]
                session["apellidos"] = user[2]
                session["cargo"] = user[11]
                session["rol"] = user[14]
                if session["rol"] == "Usuario Final":
                    return redirect(url_for("main.ver_desempenio"))
                return redirect(url_for("main.home"))
        flash("Usuario o clave incorrecto.", "errorLogin")
    return render_template("login.html", form=form_login)


@main.route("/home")
@login_required
def home():
    if session["rol"] == "Usuario Final":
        return redirect(url_for("main.ver_desempenio"))
    db = get_db()
    id = session["id_empleado"]
    id_rol = "Super Administrador"
    rows = db.execute(
        "select * from tbl_empleados where identificacion != ? and rol!=?",
        [id, id_rol],
    ).fetchall()
    db.commit()
    db.close()
    form_empleado = FormEmpleado()
    return render_template("home.html", rows=rows, form=form_empleado)


@main.route("/crear", methods=["GET", "POST"])
@login_required
def crear():
    if session["rol"] == "Usuario Final":
        return redirect(url_for("main.ver_desempenio"))
    if request.method == "POST":
        try:
            id_empleadoInput = escape(request.form["identificacion"])
            nombresInput = escape(request.form["nombres"])
            apellidosInput = escape(request.form["apellidos"])
            fechaNacimientoInput = escape(request.form["fecha_nacimiento"])
            sexoInput = escape(request.form["sexo"])
            correoInput = escape(request.form["correo"])
            direccionInput = escape(request.form["direccion"])
            telefonoInput = escape(request.form["telefono"])
            fechaIngresoInput = escape(request.form["fecha_ingreso"])
            tipoContratoInput = escape(request.form["tipo_contrato"])
            fechaTerminacionInput = escape(request.form["terminacion_contrato"])
            cargoInput = escape(request.form["cargo"])
            dependenciaInput = escape(request.form["dependencia"])
            salarioInput = escape(request.form["salario"])
            rolInput = escape(request.form["rol"])
            contraseniaInput = escape(request.form["passw"])
            db = get_db()
            contraseniaInput = SALT + contraseniaInput + id_empleadoInput
            contraseniaInput = generate_password_hash(contraseniaInput)
            db.execute(
                "INSERT INTO tbl_empleados (identificacion,nombres, apellidos, fecha_nacimiento, sexo, correo,direccion,telefono,fecha_ingreso,tipo_contrato,fecha_termin_contrato,cargo,dependencia,salario,rol,contrasenia) VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    id_empleadoInput,
                    nombresInput,
                    apellidosInput,
                    fechaNacimientoInput,
                    sexoInput,
                    correoInput,
                    direccionInput,
                    telefonoInput,
                    fechaIngresoInput,
                    tipoContratoInput,
                    fechaTerminacionInput,
                    cargoInput,
                    dependenciaInput,
                    salarioInput,
                    rolInput,
                    contraseniaInput,
                ),
            )
            db.commit()
            db.close()
            flash("Empleado Guardado Exitosamente", "successEmpleado")
            return redirect(url_for("main.home"))
        except (sqlite3.IntegrityError):
            flash("Error al Guadar los Datos. El empleado ya existe", "errorEmpleado")
    form_empleado = FormEmpleado()
    return render_template("crear.html", form=form_empleado)


@main.route("/editar/<id>", methods=["GET", "POST"])
@login_required
def editar(id):
    if session["rol"] == "Usuario Final":
        return redirect(url_for("main.ver_desempenio"))
    form_empleado = FormEmpleado()
    db = get_db()
    print(id)
    rows = db.execute(
        "SELECT * FROM tbl_empleados WHERE identificacion = ?", [id]
    ).fetchone()
    db.commit()
    print(rows)
    if request.method == "POST":
        nombresInput = escape(request.form["nombres"])
        apellidosInput = escape(request.form["apellidos"])
        fechaNacimientoInput = escape(request.form["fecha_nacimiento"])
        sexoInput = escape(request.form["sexo"])
        correoInput = escape(request.form["correo"])
        direccionInput = escape(request.form["direccion"])
        telefonoInput = escape(request.form["telefono"])
        fechaIngresoInput = escape(request.form["fecha_ingreso"])
        tipoContratoInput = escape(request.form["tipo_contrato"])
        fechaTerminacionInput = escape(request.form["terminacion_contrato"])
        cargoInput = escape(request.form["cargo"])
        dependenciaInput = escape(request.form["dependencia"])
        salarioInput = escape(request.form["salario"])
        rolInput = escape(request.form["rol"])
        db.execute(
            "UPDATE tbl_empleados SET nombres = ?, apellidos= ?, fecha_nacimiento= ?, sexo= ?, correo= ?,direccion= ?,telefono= ?,fecha_ingreso= ?,tipo_contrato= ?,fecha_termin_contrato= ?,cargo= ?,dependencia= ?,salario= ?,rol= ? WHERE identificacion = ?",
            [
                nombresInput,
                apellidosInput,
                fechaNacimientoInput,
                sexoInput,
                correoInput,
                direccionInput,
                telefonoInput,
                fechaIngresoInput,
                tipoContratoInput,
                fechaTerminacionInput,
                cargoInput,
                dependenciaInput,
                salarioInput,
                rolInput,
                id,
            ],
        )
        db.commit()
        db.close()
        flash("Empleado Modificado Exitosamente", "successEmpleado")
        return redirect(url_for("main.home"))
    if rows is None:
        flash("El empleado NO existe", "verificarEmpleado")
    if rows is not None:
        if rows[4] == "M":
            form_empleado.sexo.choices = [(rows[4], "Masculino"), ("F", "Femenino")]
        if rows[4] == "F":
            form_empleado.sexo.choices = [(rows[4], "Femenino"), ("M", "Masculino")]
        if rows[14] == "Super Administrador":
            form_empleado.rol.choices = [
                (rows[14], "Super Administrador"),
                ("Administrador", "Administrador"),
                ("Usuario Final", "Usuario Final"),
            ]
        if rows[14] == "Administrador":
            form_empleado.rol.choices = [
                (rows[14], "Administrador"),
                ("Super Administrador", "Super Administrador"),
                ("Usuario Final", "Usuario Final"),
            ]
        if rows[14] == "Usuario Final":
            form_empleado.rol.choices = [
                (rows[14], "Usuario Final"),
                ("Super Administrador", "Super Administrador"),
                ("Administrador", "Administrador"),
            ]
    return render_template("editar.html", rows=rows, form=form_empleado)


@main.route("/eliminar/<id>", methods=["GET", "POST"])
@login_required
def eliminar(id):
    db = get_db()
    db.execute("DELETE FROM tbl_empleados WHERE identificacion = ?", [id])
    db.commit()
    db.close()
    flash("Empleado Eliminado Exitosamente", "successEmpleado")
    return redirect(url_for("main.home"))


@main.route("/desempenio/<id>", methods=["GET", "POST"])
@login_required
def desempenio(id):
    if session["rol"] == "Administrador":
        return redirect(url_for("main.home"))
    if session["rol"] == "Usuario Final":
        return redirect(url_for("main.ver_desempenio"))
    db = get_db()
    rows = db.execute(
        "SELECT * FROM tbl_empleados WHERE identificacion = ?", [id]
    ).fetchone()
    db.commit()
    print(rows)
    if rows is None:
        flash("El empleado NO existe", "verificarEmpleado")
    if request.method == "POST":
        comentarioInput = escape(request.form["comentario"])
        puntajeInput = escape(request.form["puntaje"])
        idEvaluadorInput = escape(request.form["id_evaluador"])
        db.execute(
            "INSERT INTO tbl_desempenio (id_empleado,comentario,puntaje,id_evaluador) VALUES(?, ?, ?, ?)",
            ([id, comentarioInput, puntajeInput, idEvaluadorInput]),
        )

gestion_empleados/templates/cambiar_pass.html
{% extends 'template.html' %}

{% block title %} Cambiar Contraseña - Gestion de Empleados {% endblock %}
{% block name_page %} Cambiar Contraseña {% endblock %}
{% block content %}
<form action="{{url_for('main.cambiar_pass')}}" name="formCambiarPassEmpleado" method="post" autocomplete="off">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.oldPass.label }}
        {{ form.oldPass(class="form-control", placeholder="Actual Contraseña") }}
        {{ form.id_emp(value=session['id_empleado'],type="hidden") }}
    </div>

    <div class="form-group">
        {{ form.newPass.label }}
        {{ form.newPass(class="form-control", placeholder="Nueva Contraseña", minlength="8") }}

    </div>
    <div class="form-group">
        {{ form.confirmarNewPass.label }}
        {{ form.confirmarNewPass(class="form-control", placeholder="Confirmar Nueva Contraseña", minlength="8") }}

    </div>
    <center>
        {{ form.cambiarPass(class="btn btn-success") }}
    </center>
</form>
{% endblock %}

gestion_empleados/templates/crear.html
{% extends 'template.html' %}

{% block title %} Nuevo - Gestion de Empleados {% endblock %}
{% block name_page %} Nuevo Empleado {% endblock %}
{% block content %}
<form action="{{url_for('main.crear')}}" name="formCrearEmpleado" method="post" autocomplete="off">
    {{ form.hidden_tag() }}
    <div class="col-md-6">
        <div class="form-group">
            {{ form.identificacion.label }}
            {{ form.identificacion(type="number", class="form-control",
            placeholder="Identificacion") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.fecha_ingreso.label }}
            {{ form.fecha_ingreso(type="date", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.nombres.label }}
            {{ form.nombres(type="text", class="form-control", placeholder="Nombres") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.tipo_contrato.label }}
            {{ form.tipo_contrato(type="text", class="form-control", placeholder="Tipo Contrato") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.apellidos.label }}
            {{ form.apellidos(type="text", class="form-control", placeholder="Apellidos") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.terminacion_contrato.label }}
            {{ form.terminacion_contrato(type="date",class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.fecha_nacimiento.label }}
            {{ form.fecha_nacimiento(type="date",class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.cargo.label }}
            {{ form.cargo(type="text", class="form-control", placeholder="Cargo") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.sexo.label }}
            {{ form.sexo( class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.dependencia.label }}
            {{ form.dependencia(type="text", class="form-control", placeholder="Dependencia") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.correo.label }}
            {{ form.correo(type="email", class="form-control", placeholder="Correo Electronico") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.salario.label }}
            {{ form.salario(type="number", class="form-control", placeholder="Salario") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.direccion.label }}
            {{ form.direccion(type="text", class="form-control", placeholder="Direccion") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.rol.label }}
            {{ form.rol(class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.telefono.label }}
            {{ form.telefono(type="number", class="form-control", placeholder="Telefono", minlength="10" ,
            maxlength="10")
            }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.passw.label }}
            {{ form.passw(type="text", class="form-control", placeholder="Contraseña", minlength="8") }}

        </div>
    </div>

    <center>
        {{ form.guardar(class="btn btn-success") }}
    </center>
</form>

{% endblock %}

gestion_empleados/templates/desempenio.html
{% extends 'template.html' %}

{% block title %} Calificar Desempeño - Gestion de Empleados {% endblock %}
{% block name_page %} Calificar Desempeño Empleado {% endblock %}
{% block content %}
{%if rows[0]!=null %}
<form action="{{url_for('main.desempenio',id=rows[0])}}" name="formDesempenioEmpleado" method="post" autocomplete="off">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.id_empleado.label }}
        {{ form.id_empleado(value=rows[0], type="number", class="form-control",disabled="on") }}
        {{ form.id_evaluador(value=session['id_empleado'],type="hidden") }}
    </div>

    <div class="form-group">
        {{ form.comentario.label }}
        {{ form.comentario(type="text", class="form-control", placeholder="Comentario") }}

    </div>

    <div class="form-group">
        {{ form.puntaje.label }}
        {{ form.puntaje(type="number", class="form-control",min="0", max="10",maxlength="3", placeholder="Puntaje") }}

    </div>
    {{ form.id_evaluador(value=session['id_empleado'],type="hidden") }}

    <center>
        {{ form.calificar_desempenio(class="btn btn-success") }}
    </center>
</form>
{% endif %}
{% endblock %}

gestion_empleados/templates/editar.html
{% extends 'template.html' %}

{% block title %} Editar - Gestion de Empleados {% endblock %}
{% block name_page %} Editar Empleado {% endblock %}
{% block content %}
{%if rows[0]!=null %}
<form action="{{url_for('main.editar',id=rows[0])}}" name="formEditarEmpleado" method="post">
    {{ form.hidden_tag() }}
    <div class="col-md-6">
        <div class="form-group">
            {{ form.identificacion.label }}
            {{ form.identificacion(value=rows[0], type="number", class="form-control",
            disabled="on") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.fecha_ingreso.label }}
            {{ form.fecha_ingreso(value=rows[8],type="date", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.nombres.label }}
            {{ form.nombres(value=rows[1], type="text", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.tipo_contrato.label }}
            {{ form.tipo_contrato(value=rows[9], type="text", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.apellidos.label }}
            {{ form.apellidos(value=rows[2], type="text", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.terminacion_contrato.label }}
            {{ form.terminacion_contrato(value=rows[10], type="date",class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.fecha_nacimiento.label }}
            {{ form.fecha_nacimiento(value=rows[3], type="date",class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.cargo.label }}
            {{ form.cargo(value=rows[11], type="text", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.sexo.label }}
            {{ form.sexo(class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.dependencia.label }}
            {{ form.dependencia(value=rows[12], type="text", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.correo.label }}
            {{ form.correo(value=rows[5], type="email", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.salario.label }}
            {{ form.salario(value=rows[13], type="text", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.direccion.label }}
            {{ form.direccion(value=rows[6], type="text", class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.rol.label }}
            {{ form.rol(class="form-control") }}

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ form.telefono.label }}
            {{ form.telefono(value=rows[7], type="number", class="form-control",minlength="7") }}

        </div>
    </div>
    <div class="col-md-12">
        <center>
            {{ form.editar(class="btn btn-warning") }}
        </center>
    </div>
</form>
{% endif %}

{% endblock %}

gestion_empleados/templates/error.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        Error - Gestion de Empleados
    </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no name=viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet"
        href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet"
        href="{{ url_for('static', filename='bower_components/font-awesome/css/font-awesome.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/Ionicons/css/ionicons.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ url_for('static', filename='dist/css/AdminLTE.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/iCheck/square/blue.css')}}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition login-page">
    <div class=" container">
        <div style="position: absolute;top: 50%;left: 50%; transform: translate(-50%, -50%); text-align: center;">

            <h1><b>Copacol</b></h1>
            <h2><b>Sistema de Gestion de Empleados</b></h2>

            <h1 class="text-yellow"><i class="fa fa-warning text-yellow"></i> Pagina NO Encontrada.!</h1>
            <a class="btn btn-primary" href="javascript:window.history.back();">Volver</a>
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery 3 -->
    <script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js')}}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
    <!-- iCheck -->
    <script src="{{ url_for('static', filename='plugins/iCheck/icheck.min.js')}}"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
            });
        });
    </script>
</body>

</html>

gestion_empleados/templates/home.html
{% extends 'template.html' %}

{% block title %} Inicio - Gestion de Empleados {% endblock %}
{% block name_page %} Gestion de Empleados {% endblock %}
{% block content %}
<a href="{{url_for('main.crear')}}" type="button" class="btn btn-info">
    Nuevo Empleado
</a><br><br>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Listado de Empleados</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-responsive table-bordered table-hover">
            <thead>
                <tr>
                    <th>Identificaion</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Cargo</th>
                    <th>Rol</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                <tr>
                    <td>{{row[0]}}</td>
                    <td>{{row[1]}}</td>
                    <td>{{row[2]}}</td>
                    <td>{{row[11]}}</td>
                    <td>{{row[14]}}</td>
                    <td>
                        {% if session['rol']=='Super Administrador' %}

                        <a href="{{url_for('main.ver_perfil',id=row[0])}}" title="Ver">
                            <i class="fa fa-eye" style="font-size:24px;color:black"></i>
                        </a>
                        <a href="{{url_for('main.editar',id=row[0])}}" title="Editar">
                            <i class="fa fa-edit" style="font-size:24px;color:blue"></i>
                        </a>
                        <a href="{{url_for('main.eliminar',id=row[0])}}" title="Eliminar">
                            <i class="fa fa-trash" style="font-size:24px;color:red"></i>
                        </a>
                        <a href="{{url_for('main.desempenio',id=row[0])}}" title="Calificar Desempeño">
                            <i class="fa fa-line-chart" style="font-size:24px;color:green"></i>
                        </a>
                        {% endif %}
                        {% if session['rol']=='Administrador' %}
                        <a href="{{url_for('main.ver_perfil',id=row[0])}}" title="Ver">
                            <i class="fa fa-eye" style="font-size:24px;color:black"></i>
                        </a>
                        <a href="{{url_for('main.editar',id=row[0])}}" title="Editar">
                            <i class="fa fa-edit" style="font-size:24px;color:blue"></i>
                        </a>
                        {% endif %}
                    </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
    {% endblock %}

gestion_empleados/templates/ver_desempenio.html
{% extends 'template.html' %}

{% block title %} Desempeño - Gestion de Empleados {% endblock %}
{% block name_page %} Desempeño {% endblock %}
{% block content %}
<!-- Chat box -->
<br>
{%if rows[0]!= null %}
<div class="box-body chat" id="chat-box">
    <!-- chat item -->
    <div class="item">
        {% for row in rows %}
        <img src="{{ url_for('static', filename='dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
        <p class="message">
            <a class="name">
                <small class="text-muted pull-right">
                    <!-- <i class="fa fa-calendar"></i> 30/10/2021 -->
                </small>
                {{row[4]}}
            </a>
            {{row[2]}}
            <br>
            Puntaje: {{row[3]}}
        </p>
        <hr>
        {% endfor %}
    </div>
    <!-- /.item -->
</div>
<!-- /.chat -->
{%endif%}
{%if rows[0]==null %}
<div class="alert alert-warning alert-dismissible">
    <!-- <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> -->
    <h4><i class="icon fa fa-warning"></i> Alert!</h4>
    No tienes retroalimentacion de desempeño disponibles.
</div>
{% endif %}
{% endblock %}